name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:
          HUGO_VERSION: 0.102.1
          TARGET_REPO: hashing-it-out/hashing-it-out.github.io
          HUGO_EXTENDED: true
          TARGET_BRANCH: gh_pages
          TOKEN: ${{ secrets.TOKEN }}
          # HUGO_ARGS: '-t academic'
          CNAME: hashingitout.com